#!E:\calculator\Scripts\python.exe
from __future__ import absolute_import
from __future__ import division
from six.moves import range

"""
hidehead: DESCRIPTION
"""

__version__ = "$Revision: 1.3 $"

# Copyright 2005-2007 Michael M. Hoffman <hoffman+software@ebi.ac.uk>

### XXX: portable?
### N.B. python -u in shbang

import subprocess
import sys

def hidehead(args, lines=1):
    for count in range(lines):
        sys.stdout.write(sys.stdin.readline())

    return subprocess.call(args, stdin=sys.stdin)

def parse_options(args):
    from optparse import OptionParser

    global options

    usage = "%prog [OPTION]..."
    version = "%%prog %s" % __version__
    parser = OptionParser(usage=usage, version=version)
    parser.allow_interspersed_args = False

    options, args = parser.parse_args(args)

    return args

def main(args):
    args = parse_options(args)

    return hidehead(args)

def _test(*args, **kwargs):
    import doctest
    doctest.testmod(sys.modules[__name__], *args, **kwargs)

if __name__ == "__main__":
    if __debug__:
        _test()
    sys.exit(main(sys.argv[1:]))
