#!E:\calculator\Scripts\python.exe
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from six.moves import map

"""
textsum: DESCRIPTION
"""

__version__ = "$Revision: 1.3 $"

# Copyright 2005-2007 Michael M. Hoffman <hoffman+software@ebi.ac.uk>

import sys

import textinput

def textsum(*args):
    textfileitems = list(textinput.files(args))

    for textfilename, textfile in textfileitems:
        if len(textfileitems) > 1:
            print("%s:" % textfilename, end=' ')

        try:
            ints = list(map(int, textfile))
            print(sum(ints)/len(ints))
        except (ValueError, ZeroDivisionError):
            print("NA")

def parse_options(args):
    from optparse import OptionParser

    global options

    usage = "%prog [OPTION]..."
    version = "%%prog %s" % __version__
    parser = OptionParser(usage=usage, version=version)

    options, args = parser.parse_args(args)

    return args

def main(args):
    args = parse_options(args)

    return textsum(*args)

def _test(*args, **kwargs):
    import doctest
    doctest.testmod(sys.modules[__name__], *args, **kwargs)

if __name__ == "__main__":
    if __debug__:
        _test()
    sys.exit(main(sys.argv[1:]))
